# Generated by Django 5.2.4 on 2025-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('released_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'db_table': 'movies',
            },
        ),
    ]
