# Generated by Django 5.2.4 on 2025-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('bs', 'Bangla'), ('hindi', 'Hindi')], default='en', max_length=10),
        ),
    ]
