# Generated by Django 5.2.4 on 2025-07-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre'},
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
    ]
